# Customer Churn — Data Cleaning & Preprocessing

## Objective

The objective of this project is to clean and preprocess a customer churn dataset to prepare it for further data analysis and machine learning.

## Technologies Used

* Python
* Pandas
* NumPy
* Matplotlib
* Seaborn
* Jupyter Notebook

## Workflow

1. Load the dataset
2. Inspect the dataset
3. Identify missing values and duplicate records
4. Handle missing and inconsistent data
5. Clean and preprocess the data
6. Perform basic exploratory analysis
7. Prepare the cleaned dataset for further analysis

## Conclusion

The customer churn dataset was cleaned and preprocessed by identifying and handling data-quality issues. The resulting dataset is prepared for further analysis and machine learning tasks.

In [ ]:
import os
print(os.listdir('/content'))

['.config', 'sample_data']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving churn-bigml-20.csv to churn-bigml-20.csv

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'churn-bigml-20.csv', 'sample_data']

In [ ]:
import pandas as pd

df = pd.read_csv('/content/churn-bigml-20.csv')

df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [ ]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls             int64
Total day charge          float64
Total eve minutes         float64
Total eve calls             int64
Total eve charge          float64
Total night minutes       float64
Total night calls           int64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls      int64
Churn                        bool
dtype: object

In [ ]:
print("State values:")
print(df["State"].unique())

print("\nInternational plan values:")
print(df["International plan"].unique())

print("\nVoice mail plan values:")
print(df["Voice mail plan"].unique())

print("\nChurn values:")
print(df["Churn"].unique())

State values:
['LA' 'IN' 'NY' 'SC' 'HI' 'AK' 'MI' 'ID' 'VA' 'WI' 'MN' 'VT' 'MT' 'MA'
 'KY' 'CO' 'AZ' 'CA' 'WA' 'NE' 'OH' 'MO' 'AL' 'NH' 'NM' 'OR' 'TX' 'MS'
 'WY' 'FL' 'KS' 'NC' 'SD' 'OK' 'CT' 'RI' 'DE' 'UT' 'NV' 'DC' 'ME' 'IL'
 'NJ' 'MD' 'WV' 'PA' 'ND' 'AR' 'TN' 'IA' 'GA']

International plan values:
['No' 'Yes']

Voice mail plan values:
['No' 'Yes']

Churn values:
[False  True]

In [ ]:
df.to_csv('/content/churn_cleaned_task1.csv', index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'churn-bigml-20.csv', 'churn_cleaned_task1.csv', 'sample_data']

In [ ]:
cleaned_df = pd.read_csv('/content/churn_cleaned_task1.csv')

print("Shape:", cleaned_df.shape)
print("\nFirst 5 rows:")
display(cleaned_df.head())

Shape: (667, 20)

First 5 rows:

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [ ]:
from google.colab import files

files.download('/content/churn_cleaned_task1.csv')